/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AComponent {}
}

declare global {


  interface HTMLAComponentElement extends Components.AComponent, HTMLStencilElement {}
  var HTMLAComponentElement: {
    prototype: HTMLAComponentElement;
    new (): HTMLAComponentElement;
  };
  interface HTMLElementTagNameMap {
    'a-component': HTMLAComponentElement;
  }
}

declare namespace LocalJSX {
  interface AComponent extends JSXBase.HTMLAttributes<HTMLAComponentElement> {}

  interface IntrinsicElements {
    'a-component': AComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


