/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface BComponent {}
}

declare global {


  interface HTMLBComponentElement extends Components.BComponent, HTMLStencilElement {}
  var HTMLBComponentElement: {
    prototype: HTMLBComponentElement;
    new (): HTMLBComponentElement;
  };
  interface HTMLElementTagNameMap {
    'b-component': HTMLBComponentElement;
  }
}

declare namespace LocalJSX {
  interface BComponent extends JSXBase.HTMLAttributes<HTMLBComponentElement> {}

  interface IntrinsicElements {
    'b-component': BComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


